---
title: "Class16"
author: "Mari Williams (PID: A15858833)"
format: gfm
---



```{r}
library(tximport)
library(rhdf5)
library(ggplot2)
```
```{r}
folders <- dir(pattern="SRR21568*")
samples <- sub("_quant", "", folders)
files <- file.path( folders, "abundance.h5" )
names(files) <- samples

txi.kallisto <- tximport(files, type = "kallisto", txOut = TRUE)
```
```{r}
head(txi.kallisto$counts)

```
```{r}
colSums(txi.kallisto$counts)
sum(rowSums(txi.kallisto$counts)>0)

```
filtering
```{r}
to.keep <- rowSums(txi.kallisto$counts) > 0
kset.nonzero <- txi.kallisto$counts[to.keep,]

keep2 <- apply(kset.nonzero,1,sd)>0
filtered <- kset.nonzero[keep2,]
```

```{r}
pca <- prcomp(t(filtered), scale=TRUE)
summary(pca)
```

```{r}
plot(pca$x[,1], pca$x[,2],
     col=c("blue","blue","red","red"),
     xlab="PC1", ylab="PC2", pch=16)
```
```{r}
pca_df <- data.frame(
  PC1 = pca$x[,1],
  PC2 = pca$x[,2],
  sample = rownames(pca$x)
)

pca_df$group <- factor(c("A","A","B","B"))   # first 2 blue, last 2 red

ggplot(pca_df, aes(PC1, PC2, color = group)) +
  geom_point(size = 4) +
  scale_color_manual(values = c("A" = "blue", "B" = "red"))
```

```{r}
pca_df <- data.frame(
  PC1 = pca$x[,1],
  PC3 = pca$x[,3],
  sample = rownames(pca$x)
)

pca_df$group <- factor(c("A","A","B","B"))   

ggplot(pca_df, aes(PC1, PC3, color = group)) +
  geom_point(size = 4) +
  scale_color_manual(values = c("A" = "blue", "B" = "red")) 

pca_df <- data.frame(
  PC2 = pca$x[,2],
  PC3 = pca$x[,3],
  sample = rownames(pca$x)
)

pca_df$group <- factor(c("A","A","B","B"))  

ggplot(pca_df, aes(PC2, PC3, color = group)) +
  geom_point(size = 4) +
  scale_color_manual(values = c("A" = "blue", "B" = "red")) 
```

